package ch.ethz.globis.isk.WholeSystem;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import com.mongodb.client.model.Filters;

import ch.ethz.globis.isk.mongodb.Database;
import ch.ethz.globis.isk.mongodb.Table;
import ch.ethz.globis.isk.xmldb.api.BaseXClient.Query;




/**
*
* @author panuyabalasuntharam
*/
public class WPanel extends javax.swing.JPanel {
	
	private ch.ethz.globis.isk.mongodb.Database db2;
	private ch.ethz.globis.isk.xmldb.Database db3;

   /**
    * Creates new form Panel
    */
   public WPanel(ch.ethz.globis.isk.mongodb.Database db2, 
			ch.ethz.globis.isk.xmldb.Database db3) {
	   this.db2 = db2;
	   this.db3 = db3;
	   
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jPanel1 = new javax.swing.JPanel();
       jPanel2 = new javax.swing.JPanel();
       jPanel4 = new javax.swing.JPanel();
       jPanel5 = new javax.swing.JPanel();
       
       jTextField18 = new javax.swing.JTextField();
       jTextField14 = new javax.swing.JTextField();
       jTextField15 = new javax.swing.JTextField();
       jTextField8 = new javax.swing.JTextField();
       jTextField9 = new javax.swing.JTextField();
       jTextField10 = new javax.swing.JTextField();
       xtextField1 = new javax.swing.JTextField();
       xtextField3 = new javax.swing.JTextField();
       xtextField2 = new javax.swing.JTextField();
       
       jLabel7 = new javax.swing.JLabel();
       jLabel9 = new javax.swing.JLabel();
       jLabel6 = new javax.swing.JLabel();
       jLabel1 = new javax.swing.JLabel();
       jLabel5 = new javax.swing.JLabel();
       jLabel4 = new javax.swing.JLabel();
       jLabel2 = new javax.swing.JLabel();
       jLabel3 = new javax.swing.JLabel();
       
       jSeparator15 = new javax.swing.JSeparator();
       jSeparator16 = new javax.swing.JSeparator();
       jSeparator17 = new javax.swing.JSeparator();
       jSeparator1 = new javax.swing.JSeparator();
       jSeparator9 = new javax.swing.JSeparator();
       jSeparator10 = new javax.swing.JSeparator();
       jSeparator12 = new javax.swing.JSeparator();
       jSeparator13 = new javax.swing.JSeparator();
       jSeparator11 = new javax.swing.JSeparator();
       jSeparator14 = new javax.swing.JSeparator();
       
       
       mPublicationButton = new javax.swing.JButton();
       mPreButton = new javax.swing.JButton();
       
       xPublicationButton = new javax.swing.JButton();
       
       jButton1 = new javax.swing.JButton();
       jButton4 = new javax.swing.JButton();
       jButton5 = new javax.swing.JButton();
       jButton6 = new javax.swing.JButton();
       jButton7 = new javax.swing.JButton();
       jButton9 = new javax.swing.JButton();
       jButton8 = new javax.swing.JButton();
       jButton10 = new javax.swing.JButton();
       jButton11 = new javax.swing.JButton();
       jButton12 = new javax.swing.JButton();
       jButton13 = new javax.swing.JButton();
       jButton14 = new javax.swing.JButton();
       jButton15 = new javax.swing.JButton();
       jButton16 = new javax.swing.JButton();
       jButton17 = new javax.swing.JButton();
       jButton18 = new javax.swing.JButton();
       jButton19 = new javax.swing.JButton();
       
       
       jButton21 = new javax.swing.JButton();
       jButton22 = new javax.swing.JButton();
       jButton23 = new javax.swing.JButton();
       
       
       //------------------------------------------------------------------------------------------------------------------//
       
       xSerButton = new javax.swing.JButton();
       xProButton = new javax.swing.JButton();
       xInProButton = new javax.swing.JButton();
       xConfButton = new javax.swing.JButton();
       xConfEdButton = new javax.swing.JButton();
       xAuthEdButton = new javax.swing.JButton();
       xPublisherButton = new javax.swing.JButton();
       xQuery1Button = new javax.swing.JButton();
       xQuery2Button = new javax.swing.JButton();
       xQuery3Button = new javax.swing.JButton();
       xQuery4Button = new javax.swing.JButton();
       xQuery9Button = new javax.swing.JButton();
       xQuery10Button = new javax.swing.JButton();
       xQuery8Button = new javax.swing.JButton();
       xQuery11Button = new javax.swing.JButton();
       xQuery6Button = new javax.swing.JButton();
       xQuery7Button = new javax.swing.JButton();
       xQuery5Button = new javax.swing.JButton();
       xQuery13Button = new javax.swing.JButton();
       xQuery14Button = new javax.swing.JButton();
       xQuery12Button = new javax.swing.JButton();
       jButton45 = new javax.swing.JButton();
       jButton46 = new javax.swing.JButton();
       jButton47 = new javax.swing.JButton();
       jButton48 = new javax.swing.JButton();      
       jButton49 = new javax.swing.JButton();
       jButton50 = new javax.swing.JButton();
       jButton51 = new javax.swing.JButton();
       jButton52 = new javax.swing.JButton();
       jButton53 = new javax.swing.JButton();
       jButton54 = new javax.swing.JButton();
       jButton55 = new javax.swing.JButton();
       jButton56 = new javax.swing.JButton();
       jButton57 = new javax.swing.JButton();
       jButton58 = new javax.swing.JButton();
       jButton59 = new javax.swing.JButton();
       jButton60 = new javax.swing.JButton();
       jButton61 = new javax.swing.JButton();
       jButton62 = new javax.swing.JButton();
       jButton63 = new javax.swing.JButton();
       jButton64 = new javax.swing.JButton();
       jButton65 = new javax.swing.JButton();
       jButton66 = new javax.swing.JButton();
       
       
       setBackground(new java.awt.Color(97, 212, 195));
       setForeground(new java.awt.Color(255, 255, 255));
       setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

       
       
       
       

       jButton48.setText("InProceddings");
       jButton48.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton48ActionPerformed(evt);
           }
       });

       jButton66.setText("9. Auth/Ed Count");
       jButton66.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton66ActionPerformed(evt);
           }
       });

       jButton64.setText("14. Pub of Pro");
       jButton64.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton64ActionPerformed(evt);
           }
       });

       jButton63.setText("Conf Editions");
       jButton63.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton63ActionPerformed(evt);
           }
       });

      

       jButton46.setText("5. Short. P Authors");

       jButton55.setText("6. Avg Pub");
       jButton55.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton55ActionPerformed(evt);
           }
       });

       jButton53.setText("Conferences");
       jButton53.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton53ActionPerformed(evt);
           }
       });

       jButton52.setText("11. Pub of Conf");
       jButton52.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton52ActionPerformed(evt);
           }
       });

       jButton45.setText("13. Pub Auth last");
       jButton45.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton45ActionPerformed(evt);
           }
       });

       
       
       

       jButton54.setText("Publishers");
       jButton54.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton54ActionPerformed(evt);
           }
       });

       jButton50.setText("2. Pub by title");
       jButton50.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton50ActionPerformed(evt);
           }
       });

       jButton61.setText("4. Co-Authors");
       jButton61.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton61ActionPerformed(evt);
           }
       });

       jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
       jLabel7.setForeground(new java.awt.Color(255, 255, 255));

       jButton49.setText("Series");
       jButton49.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton49ActionPerformed(evt);
           }
       });

       jButton47.setText("1.Pub by ID");

       jButton65.setText("Publications");

       jButton57.setText("10. Auth of Conf");
       jButton57.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton57ActionPerformed(evt);
           }
       });
       
      

       jButton59.setText("Authors/Editors");
       jButton59.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton59ActionPerformed(evt);
           }
       });

       jButton62.setText("7. PubCount y");
       jButton62.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton62ActionPerformed(evt);
           }
       });

       

       jButton56.setText("8. PubCount Conf");

       jButton51.setText("3. Q2 ord by title");
       jButton51.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton51ActionPerformed(evt);
           }
       });

       jButton60.setText("12. Auth = Ed");

       jButton58.setText("Proceedings");
       jButton58.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton58ActionPerformed(evt);
           }
       });

      
       
       
       
       
       //------------------------------------------------------------------------------------//
       
       xInProButton.setText("InProceddings");
       xInProButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xInProActionPerformed(evt);
           }
       });
       
       xPublisherButton.setText("Publishers");
       xPublisherButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xPublisherActionPerformed(evt);
           }
       });
       
       xProButton.setText("Proceedings");
       xProButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xProActionPerformed(evt);
           }
       });
       
       xSerButton.setText("Series");
       xSerButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xSerActionPerformed(evt);
           }
       });
       
       xAuthEdButton.setText("Authors/Editors");
       xAuthEdButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xAuthEdActionPerformed(evt);
           }
       });
       
       xConfEdButton.setText("Conf Editions");
       xConfEdButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xConfEdActionPerformed(evt);
           }
       });
       
       xPublicationButton.setText("Publications");
       xPublicationButton.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
               xPublicationActionPerformed(evt);
           }
       });
       
       xConfButton.setText("Conferences");
       xConfButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xConfActionPerformed(evt);
           }
       });
       
       xQuery1Button.setText("1.Pub by ID");
       xQuery1Button.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xQuery1ActionPerformed(evt);
           }
       });
       
       xQuery2Button.setText("2. Pub by title");
       xQuery2Button.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xQuery2ActionPerformed(evt);
           }
       });
       
       xQuery3Button.setText("3. Q2 ord by title");
       xQuery3Button.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xQuery3ActionPerformed(evt);
           }
       });
       
       xQuery4Button.setText("4. Co-Authors");
       xQuery4Button.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xQuery4ActionPerformed(evt);
           }
      
       });
       
       xQuery5Button.setText("5. Short. P Authors");
       xQuery5Button.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xQuery5ActionPerformed(evt);
           }
       });
       
       
       
       xQuery6Button.setText("6. Avg Pub");
       xQuery6Button.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xQuery6ActionPerformed(evt);
           }
       });
       
       
       xQuery7Button.setText("7. PubCount y");
       xQuery7Button.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xQuery7ActionPerformed(evt);
           }
       });
       
       xQuery8Button.setText("8. PubCount Conf");
       xQuery8Button.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xQuery8ActionPerformed(evt);
           }
       });
       
       xQuery9Button.setText("9. Auth/Ed Count");
       xQuery9Button.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xQuery9ActionPerformed(evt);
           }
       });
       
       xQuery10Button.setText("10. Auth of Conf");
       xQuery10Button.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xQuery10ActionPerformed(evt);
           }
       });
       
       xQuery11Button.setText("11. Pub of Conf");
       xQuery11Button.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xQuery11ActionPerformed(evt);
           }
       });
       
       xQuery12Button.setText("12. Auth = Ed");
       xQuery12Button.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xQuery12ActionPerformed(evt);
           }
       });
       
       xQuery13Button.setText("13. Pub Auth last");
       xQuery13Button.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xQuery13ActionPerformed(evt);
           }
       });
       
       xQuery14Button.setText("14. Pub of Pro");
       xQuery14Button.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               xQuery14ActionPerformed(evt);
           }
       });
       
       

      
       
       add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 330, 620));
       
      

      

       
      

      
       

      
       

       
       

       

     //------------------------------------------------------------------------------------//

       jButton1.setText("Series");
       jButton1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton1ActionPerformed(evt);
           }
       });
       add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 150, -1));

       mPublicationButton.setText("Publications");
       add(mPublicationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 150, -1));
       mPublicationButton.addActionListener(new ActionListener() {
    	   public void actionPerformed(ActionEvent evt) {
    	           mpublicationsButtonActionPerformed(evt);
    	       }
    	   });

       mPreButton.setText("Proceedings");
       mPreButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
        	   mproceedingsButtonActionPerformed(evt);
           }
       });
       add(mPreButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 150, -1));

       jButton4.setText("InProceddings");
       jButton4.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton4ActionPerformed(evt);
           }
       });
       add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 150, -1));

       jButton5.setText("Conferences");
       jButton5.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton5ActionPerformed(evt);
           }
       });
       add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 150, -1));

       jButton6.setText("Conf Editions");
       jButton6.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton6ActionPerformed(evt);
           }
       });
       add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 150, -1));

       jButton7.setText("Authors/Editors");
       jButton7.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton7ActionPerformed(evt);
           }
       });
       add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 150, -1));

       jButton9.setText("Publishers");
       jButton9.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton9ActionPerformed(evt);
           }
       });
       add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 150, -1));

       jButton8.setText("1.Pub by ID");
       add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 150, -1));

       jButton10.setText("2. Pub by title");
       jButton10.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton10ActionPerformed(evt);
           }
       });
       add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 150, -1));

       jButton11.setText("3. Q2 ord by title");
       jButton11.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton11ActionPerformed(evt);
           }
       });
       add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

       jButton12.setText("4. Co-Authors");
       jButton12.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton12ActionPerformed(evt);
           }
       });
       add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 150, -1));

       jButton13.setText("9. Auth/Ed Count");
       jButton13.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton13ActionPerformed(evt);
           }
       });
       add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 150, -1));

       jButton14.setText("10. Auth of Conf");
       jButton14.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton14ActionPerformed(evt);
           }
       });
       add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 150, -1));

       jButton15.setText("8. PubCount Conf");
       add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 150, -1));

       jButton16.setText("11. Pub of Conf");
       jButton16.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton16ActionPerformed(evt);
           }
       });
       add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 150, -1));

       jButton17.setText("6. Avg Pub");
       jButton17.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton17ActionPerformed(evt);
           }
       });
       add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 150, -1));

       jButton18.setText("7. PubCount y");
       jButton18.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton18ActionPerformed(evt);
           }
       });
       add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 150, -1));

       jButton19.setText("5. Short. P Authors");
       add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 150, -1));

       jButton21.setText("13. Pub Auth last");
       jButton21.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton21ActionPerformed(evt);
           }
       });
       add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 150, -1));

       jButton22.setText("14. Pub of Pro");
       jButton22.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton22ActionPerformed(evt);
           }
       });
       add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, 150, -1));

       jButton23.setText("12. Auth = Ed");
       add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 150, -1));

       
       
       
       
       
       
       
       
       
       
       
       
       jSeparator15.setForeground(new java.awt.Color(255, 255, 255));
       jPanel1.setBackground(new java.awt.Color(36, 47, 65));
       jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
       add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 0, -1, 529));

       jPanel2.setBackground(new java.awt.Color(36, 47, 65));

       jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
       jLabel9.setForeground(new java.awt.Color(255, 255, 255));
       jTextField18.setBackground(new java.awt.Color(36, 47, 65));
       jTextField18.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
       jTextField18.setForeground(new java.awt.Color(255, 255, 255));
       jTextField18.setText("Enter  ");
       jTextField18.setBorder(null);
       jTextField18.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseClicked(java.awt.event.MouseEvent evt) {
               jTextField18MouseClicked(evt);
           }
       });
       jTextField18.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField18ActionPerformed(evt);
           }
       });

       jTextField14.setBackground(new java.awt.Color(36, 47, 65));
       jTextField14.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
       jTextField14.setForeground(new java.awt.Color(255, 255, 255));
       jTextField14.setText("Enter  ");
       jTextField14.setBorder(null);
       jTextField14.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseClicked(java.awt.event.MouseEvent evt) {
               jTextField14MouseClicked(evt);
           }
       });
       jTextField14.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField14ActionPerformed(evt);
           }
       });

       jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
       jLabel6.setForeground(new java.awt.Color(255, 255, 255));
       jLabel6.setText("ZooDB");

       jTextField15.setBackground(new java.awt.Color(36, 47, 65));
       jTextField15.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
       jTextField15.setForeground(new java.awt.Color(255, 255, 255));
       jTextField15.setText("Enter  ");
       jTextField15.setBorder(null);
       jTextField15.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseClicked(java.awt.event.MouseEvent evt) {
               jTextField15MouseClicked(evt);
           }
       });
       jTextField15.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField15ActionPerformed(evt);
           }
       });
       
       jSeparator16.setForeground(new java.awt.Color(255, 255, 255));
       

       

       jSeparator14.setForeground(new java.awt.Color(255, 255, 255));
       

       
       jSeparator13.setForeground(new java.awt.Color(255, 255, 255));
       jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
       jLabel5.setForeground(new java.awt.Color(255, 255, 255));
       jLabel5.setText("XML");
       jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 300, 47));

       jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
       jLabel4.setForeground(new java.awt.Color(255, 255, 255));
       
   
       jSeparator17.setForeground(new java.awt.Color(255, 255, 255));
       
       

       jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
   
       
       javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
       jPanel2.setLayout(jPanel2Layout);
       jPanel2Layout.setHorizontalGroup(
           jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel2Layout.createSequentialGroup()
               .addGap(17, 17, 17)
               .addComponent(jLabel9)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
           .addGroup(jPanel2Layout.createSequentialGroup()
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addGap(10, 10, 10)
                       .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addGap(10, 10, 10)
                       .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addGap(10, 10, 10)
                       .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addGap(10, 10, 10)
                       .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addGap(140, 140, 140)
                       .addComponent(jButton58, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addComponent(jButton65, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addGap(140, 140, 140)
                       .addComponent(jButton53, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addGap(140, 140, 140)
                       .addComponent(jButton59, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addComponent(jButton63, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jButton54, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addGap(140, 140, 140)
                       .addComponent(jButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addGap(140, 140, 140)
                       .addComponent(jButton56, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addComponent(jButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addGap(140, 140, 140)
                       .addComponent(jButton66, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addComponent(jButton51)
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addGap(140, 140, 140)
                       .addComponent(jButton57, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addGap(140, 140, 140)
                       .addComponent(jButton52, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addComponent(jButton61, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addGap(140, 140, 140)
                       .addComponent(jButton60, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jButton55, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addGap(140, 140, 140)
                       .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addComponent(jButton62, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addGap(140, 140, 140)
                       .addComponent(jButton64, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addGap(10, 10, 10)
                       .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGap(0, 0, Short.MAX_VALUE))
       );
       jPanel2Layout.setVerticalGroup(
           jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel2Layout.createSequentialGroup()
               .addGap(18, 18, 18)
               .addComponent(jLabel9)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addGap(40, 40, 40)
                       .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(4, 4, 4)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addGap(10, 10, 10)
                       .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGap(4, 4, 4)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addGroup(jPanel2Layout.createSequentialGroup()
                       .addGap(10, 10, 10)
                       .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(8, 8, 8)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jButton58)
                   .addComponent(jButton65))
               .addGap(1, 1, 1)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jButton48)
                   .addComponent(jButton53))
               .addGap(1, 1, 1)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jButton59)
                   .addComponent(jButton63))
               .addGap(1, 1, 1)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jButton54)
                   .addComponent(jButton49))
               .addGap(1, 1, 1)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jButton47)
                   .addComponent(jButton56))
               .addGap(1, 1, 1)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jButton50)
                   .addComponent(jButton66))
               .addGap(1, 1, 1)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jButton51)
                   .addComponent(jButton57))
               .addGap(1, 1, 1)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jButton52)
                   .addComponent(jButton61))
               .addGap(1, 1, 1)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jButton60)
                   .addComponent(jButton46))
               .addGap(1, 1, 1)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jButton55)
                   .addComponent(jButton45))
               .addGap(1, 1, 1)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jButton62)
                   .addComponent(jButton64))
               .addGap(1, 1, 1)
               .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(16, 16, 16))
       );

       add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 620));

       jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
       jLabel1.setForeground(new java.awt.Color(255, 255, 255));
       add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 270, 47));
       add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1057, 243, 300, 0));

       jPanel4.setBackground(new java.awt.Color(36, 47, 65));
       jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

       javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
       jPanel5.setLayout(jPanel5Layout);
       jPanel5Layout.setHorizontalGroup(
           jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 0, Short.MAX_VALUE)
       );
       jPanel5Layout.setVerticalGroup(
           jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 40, Short.MAX_VALUE)
       );

       

       xtextField1.setBackground(new java.awt.Color(36, 47, 65));
       xtextField1.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
       xtextField1.setForeground(new java.awt.Color(255, 255, 255));
       xtextField1.setText("Enter  ");
       xtextField1.setBorder(null);
       xtextField1.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseClicked(java.awt.event.MouseEvent evt) {
               jTextField11MouseClicked(evt);
           }
       });
       xtextField1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField11ActionPerformed(evt);
           }
       });
       jPanel4.add(xQuery5Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 150, -1));
       jPanel4.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 260, -1));
       jPanel4.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 260, -1));
       jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 270, 47));
       jPanel4.add(xQuery13Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 150, -1));
       jPanel4.add(xQuery1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 150, -1));
       jPanel4.add(xtextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 260, 26));
       jPanel4.add(xQuery9Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 150, -1));
       jPanel4.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 260, -1));
       jPanel4.add(xInProButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 150, -1));
       jPanel4.add(xSerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 150, -1));
       jPanel4.add(xQuery3Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));
       jPanel4.add(xQuery11Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 150, -1));
       jPanel4.add(xConfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 150, -1));
       jPanel4.add(xPublisherButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 150, -1));
       jPanel4.add(xQuery6Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 150, -1));
       jPanel4.add(xQuery8Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 150, -1));
       jPanel4.add(xQuery10Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 150, -1));
       jPanel4.add(xProButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 150, -1));
       jPanel4.add(xtextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 260, 26));
       jPanel4.add(xQuery2Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 150, -1));
       jPanel4.add(xAuthEdButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 150, -1));
       jPanel4.add(xQuery12Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 150, -1));
       jPanel4.add(xQuery7Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 150, -1));
       jPanel4.add(xQuery4Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 150, -1));
       jPanel4.add(xConfEdButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 150, -1));
       jPanel4.add(xQuery14Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 150, -1));
       jPanel4.add(xPublicationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, -1));

       xtextField2.setBackground(new java.awt.Color(36, 47, 65));
       xtextField2.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
       xtextField2.setForeground(new java.awt.Color(255, 255, 255));
       xtextField2.setText("Enter  ");
       xtextField2.setBorder(null);
       xtextField2.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseClicked(java.awt.event.MouseEvent evt) {
               jTextField12MouseClicked(evt);
           }
       });
       xtextField2.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField12ActionPerformed(evt);
           }
       });
       
       xtextField3.setBackground(new java.awt.Color(36, 47, 65));
       xtextField3.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
       xtextField3.setForeground(new java.awt.Color(255, 255, 255));
       xtextField3.setText("Enter  ");
       xtextField3.setBorder(null);
       xtextField3.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseClicked(java.awt.event.MouseEvent evt) {
               jTextField13MouseClicked(evt);
           }
       });
       xtextField3.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField13ActionPerformed(evt);
           }
       });
       jPanel4.add(xtextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 260, 30));
       

       

       jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
       jLabel2.setForeground(new java.awt.Color(255, 255, 255));
       jLabel2.setText("Domain Objects");
       add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 300, 47));

       jTextField8.setBackground(new java.awt.Color(97, 212, 195));
       jTextField8.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
       jTextField8.setForeground(new java.awt.Color(255, 255, 255));
       jTextField8.setText("Enter  ");
       jTextField8.setBorder(null);
       jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseClicked(java.awt.event.MouseEvent evt) {
               jTextField8MouseClicked(evt);
           }
       });
       jTextField8.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField8ActionPerformed(evt);
           }
       });
       add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 260, 26));

       jTextField9.setBackground(new java.awt.Color(97, 212, 195));
       jTextField9.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
       jTextField9.setForeground(new java.awt.Color(255, 255, 255));
       jTextField9.setText("Enter  ");
       jTextField9.setBorder(null);
       jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseClicked(java.awt.event.MouseEvent evt) {
               jTextField9MouseClicked(evt);
           }
       });
       jTextField9.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField9ActionPerformed(evt);
           }
       });
       add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 260, 26));

       jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
       add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 260, -1));

       jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
       add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 260, -1));

       jTextField10.setBackground(new java.awt.Color(97, 212, 195));
       jTextField10.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
       jTextField10.setForeground(new java.awt.Color(255, 255, 255));
       jTextField10.setText("Enter  ");
       jTextField10.setBorder(null);
       jTextField10.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseClicked(java.awt.event.MouseEvent evt) {
               jTextField10MouseClicked(evt);
           }
       });
       jTextField10.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField10ActionPerformed(evt);
           }
       });
       add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 260, 30));

       jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
       add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 260, -1));
       
       jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
       jLabel3.setForeground(new java.awt.Color(255, 255, 255));
       jLabel3.setText("MongoDB");
       add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 300, 47));
   }// </editor-fold>                        

   private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {                                            
       // TODO add your handling code here:
   }                                           

   private void jTextField8MouseClicked(java.awt.event.MouseEvent evt) {                                         
       // TODO add your handling code here:
   }                                        

   private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {                                            
       // TODO add your handling code here:
   }                                           

   private void jTextField9MouseClicked(java.awt.event.MouseEvent evt) {                                         
       // TODO add your handling code here:
   }                                        

   private void jTextField10MouseClicked(java.awt.event.MouseEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {                                             
       // TODO add your handling code here:
   }                                            

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
   }                                        

                                          

   private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
   }                                        

   private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
   }                                        

   private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
   }                                        

   private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
   }                                        

   private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
   }                                        

   private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jTextField11MouseClicked(java.awt.event.MouseEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {                                             
       // TODO add your handling code here:
   }                                            

   private void jTextField12MouseClicked(java.awt.event.MouseEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {                                             
       // TODO add your handling code here:
   }                                            

   private void jTextField13MouseClicked(java.awt.event.MouseEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {                                             
       // TODO add your handling code here:
   }    
   
   
   
   
   //-----------------------------------------------------------------------------------------//

   private void xSerActionPerformed(java.awt.event.ActionEvent evt) {                                          
	   new ch.ethz.globis.isk.xmldb.Table(
   			db3,
   			"series.xml",
   			null,
   			"Series",
   			new String[] { "Name", "Publications" },
   			new String[] { "id", "pid" },
   			true
   	);
   }                                         

   private void xProActionPerformed(java.awt.event.ActionEvent evt) {                                          
	   new ch.ethz.globis.isk.xmldb.Table(
   			db3,
   			"proceedings.xml",
   			null,
   			"Proceedings",
   			new String[] { "ID", "Title", "Conference", "Conference Edition", "Publisher", "Series", "ISBN", "Editors"  },
   			new String[] { "id", "title", "cid", "ceid", "publisher", "sid", "isbn", "editor"  },
   			true
   	);
   }                                         

   private void xInProActionPerformed(java.awt.event.ActionEvent evt) {                                          
	   new ch.ethz.globis.isk.xmldb.Table(
   			db3,
   			"inproceedings.xml",
   			null,
   			"Inproceedings",
   			new String[] { "ID", "Title", "Proceedings", "Authors" },
   			new String[] { "id", "title", "pid", "author" },
   			true
   	);
   }                                         

   private void xConfActionPerformed(java.awt.event.ActionEvent evt) {                                          
	   new ch.ethz.globis.isk.xmldb.Table(
   			db3,
   			"conferences.xml",
   			null,
   			"Conferences",
   			new String[] { "Name", "Editions" },
   			new String[] { "id", "ceid" },
   			true
   	);
   }                                         

   private void xConfEdActionPerformed(java.awt.event.ActionEvent evt) {                                          
	   new ch.ethz.globis.isk.xmldb.Table(
   			db3,
   			"conferenceEditions.xml",
   			null,
   			"ConferenceEditions",
   			new String[] { "Year", "Conference", "Proceedings" },
   			new String[] { "id", "cid", "pid" },
   			true
   	);
   }                                         

   private void xAuthEdActionPerformed(java.awt.event.ActionEvent evt) {                                          
	   new ch.ethz.globis.isk.xmldb.Table(
   			db3,
   			"persons.xml",
   			null,
   			"Authors/Editors",
   			new String[] { "Name", "Authored Publications", "Edited Publications" },
   			new String[] { "id", "iid", "pid" },
   			true
   	);
   }                                         

   private void xPublisherActionPerformed(java.awt.event.ActionEvent evt) {                                          
	   new ch.ethz.globis.isk.xmldb.Table(
   			db3,
   			"publishers.xml",
   			null,
   			"Publishers",
   			new String[] { "Name", "Publications" },
   			new String[] { "id", "pid" },
   			true
   	);
   }    

   private void xQuery1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	   String id = xtextField1.getText();
   	String input =
   	  "let $publications := doc('publications.xml')/root//* "
		+ "return <root>{ "
		+   "for $p in $publications "
		+   "return "
		+     "if (contains($p/id, '" + id + "')) "
		+     "then $p "
		+     "else () "
		+ "}</root> ";
   	Query query = db3.execute(input);
   	
   	new ch.ethz.globis.isk.xmldb.Table(
   			db3,
   			null,
   			query,
   			"Publications by id",
   			new String[] { "ID", "Title" },
   			new String[] { "id", "title" },
   			false
   	);
   }  
 
   private void xQuery2ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	   String id = xtextField1.getText();
   	int beginOffset = 0;
   	int endOffset = 0;
   	try {
	    	beginOffset = Integer.parseInt(xtextField2.getText());
	    	endOffset = Integer.parseInt(xtextField3.getText());
   	} catch (Exception e) {
   		e.printStackTrace();
   	}
   	String input =
		 "let $publications := doc('publications.xml')/root//*[contains(title, '" + id + "')] "
		+"return <root>{ "
		+  "subsequence($publications, " + beginOffset +  ", " + (endOffset - beginOffset) + ") "
		+"}</root> ";
   	Query query = db3.execute(input);
   	
	new ch.ethz.globis.isk.xmldb.Table(
   			db3,
   			null,
   			query,
   			"Publications by id limited",
   			new String[] { "ID", "Title" },
   			new String[] { "id", "title" },
   			false
   	);
   }                                         

   private void xQuery3ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	   String id = xtextField1.getText();
   	int beginOffset = 0;
   	int endOffset = 0;
   	try {
	    	beginOffset = Integer.parseInt(xtextField2.getText());
	    	endOffset = Integer.parseInt(xtextField3.getText());
   	} catch (Exception e) {
   		e.printStackTrace();
   	}
   	String input =
		 "let $publications := doc('publications.xml')/root//*[contains(title, '" + id + "')] "
		+"return <root>{ "
		+  "let $sorted := for $publication in $publications "
		+     "order by $publication/title/text() "
		+     "return $publication "
		+  "return subsequence($sorted, " + beginOffset +  ", " + (endOffset - beginOffset) + ") "
		+"}</root> ";
   	Query query = db3.execute(input);
   	
	new ch.ethz.globis.isk.xmldb.Table(
   			db3,
   			null,
   			query,
   			"Publications by id sorted limited",
   			new String[] { "ID", "Title" },
   			new String[] { "id", "title" },
   			false
   	);
   }                                         

   private void xQuery4ActionPerformed(java.awt.event.ActionEvent evt) {   
	   String authorId = xtextField1.getText();
   	String input =
		 "let $author := doc('persons.xml')/root//*[id = '" + authorId + "'] "
		+"return <root>{ "
		+  "<author>{ "
		+    "$author/id, "
		+    "for $i in doc('inproceedings.xml')/root//*[id = $author//iid/text()] "
		+    "return "
		+      "for $coAuthor in $i//author "
		+      "return "
		+        "if ($coAuthor/text() = $author/id/text()) "
		+        "then () "
		+        "else <coAuthor>{$coAuthor/text()}</coAuthor> "
		+  "}</author> "
		+"}</root> ";
   	Query query = db3.execute(input);
   	
	new ch.ethz.globis.isk.xmldb.Table(
   			db3,
   			null,
   			query,
   			"Co-Authors",
   			new String[] { "Author", "Co-Authors" },
   			new String[] { "id", "coAuthor" },
   			false
   	);
   }  
   
   private void xQuery5ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	   String author1Id = xtextField1.getText();
   	String author2Id = xtextField2.getText();
   	String input =
   	 "declare function local:shortestPath($authors, $target, $depth) { "
   	+  "if ($depth > 20) "
   	+  "then 'The authors do not have anything in common' "
   	+  "else "
   	+    "if (some $author in $authors satisfies $author/id/text() = $target/id/text()) "
   	+    "then $depth "
   	+    "else local:shortestPath(doc('coAuthors.xml')/root//*[id/text() = $authors//coAuthor/text()], $target, $depth + 1) "
   	+"}; "
   	+"let $coAuthors := doc('coAuthors.xml')/root//*, "
   	+"$author := $coAuthors[id = '" + author1Id + "'], "
   	+"$target := $coAuthors[id = '" + author2Id + "'] "
   	+"return <root>{ "
   	+  "<item>{ "
   	+    "<shortestPath>{ "
   	+      "local:shortestPath($author, $target, 0) "
   	+    "}</shortestPath> "
   	+  "}</item> "
   	+"}</root> ";
   	Query query = db3.execute(input);
   	
	new ch.ethz.globis.isk.xmldb.Table(
   			db3,
   			null,
   			query,
   			"Shortest Path",
   			new String[] { "Shortest Path" },
   			new String[] { "shortestPath" },
   			false
   	);
   }  
   
   private void xQuery6ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	   Query query = db3.executeFile("query6.xq");
   	
		new ch.ethz.globis.isk.xmldb.Table(
   			db3,
   			null,
   			query,
   			"Global average number of authors per publication",
   			new String[] { "Avg number of authors" },
   			new String[] { "avg" },
   			false
   	);
   }                                         

   private void xQuery7ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	   int beginYear = 0;
   	int endYear = 0;
   	try {
   		beginYear = Integer.parseInt(xtextField1.getText());
   		endYear = Integer.parseInt(xtextField2.getText());
   	} catch (Exception e) {
   		e.printStackTrace();
   	}
   	
   	if (beginYear > endYear){
   		int temp = beginYear;
   		beginYear = endYear;
   		endYear = temp;
   	}
   	
   	String beginStr = Integer.toString(beginYear);
   	String endStr   = Integer.toString(endYear);
   	
   	
   	String input = "let $inproceedings := doc('publications.xml')/root/inproceedings[(ceid >= " + beginYear + ") and (ceid <= " + endYear + ")] "
   			+ "return <root>{ "
   			+ "for $year in distinct-values($inproceedings/ceid) "
   			+ "order by $year "
   			+ "return "
   			+ "<result> "
   			+ "<year>{ "
   			+ "$year "
   			+ "}</year> "
   			+ "<num>{ "
   			+ "count($inproceedings[ceid = $year]) "
   			+ "}</num> "
   			+ "</result> "
   			+ "}</root>";
   	
   	
   	Query query = db3.execute(input);
   	
	new ch.ethz.globis.isk.xmldb.Table(
   			db3,
   			null,
   			query,
   			"Number of publications per year between " + beginStr + " and " + endStr + ".",
   			new String[] { "Year", "Number" },
   			new String[] { "year", "num" },
   			false
   	);
   } 
   
   private void xQuery8ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	// e.g. "ICPP"
   	String confID = xtextField1.getText();
   	
   	
   	String input = "let $publications := doc('publications.xml')/root "
   			+ "return <root>{ "
   			+ 	"<item>{ "
   			+ 		"<num>{ "
   			+ 			"for $p in $publications/proceedings[cid = '" + confID + "'] "
   			+ 			"return ( "
   			+ 				"count( "
   			+ 					"for $ip in  $publications/inproceedings "
   			+ 					"where $ip/pid = $p/id "
   			+ 					"return $ip "
   			+ 				") "
   			+ 			") "
   			+ 		"}</num> "
   			+ 	"}</item> "
   			+ "}</root>";
   	
   	Query query = db3.execute(input);
   	
	new ch.ethz.globis.isk.xmldb.Table(
   			db3,
   			null,
   			query,
   			"Number of publications for conference " + confID + ". ",
   			new String[] { "Total" },
   			new String[] { "num" },
   			false
   	);
   }  

   private void xQuery9ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	   String confID = xtextField1.getText();
   	
   	String input =
   			"let $proceedings := doc('proceedings.xml')/root//*[cid/text() = '" + confID + "'], "
   			+ "$inproceedings := doc('inproceedings.xml')/root//*[pid/text() = $proceedings/id/text()] "
   			+ "return <root><item><count>{count(distinct-values($proceedings/editor/text() | $inproceedings/author/text()))}</count></item></root> ";
       	
       	Query query = db3.execute(input);
       	
       	new ch.ethz.globis.isk.xmldb.Table(
       			db3,
       			null,
       			query,
       			"Count of authors and editors of conference " + confID + ".",
       			new String[] { "Count" },
       			new String[] { "count" },
       			false
       	);
   }                                         

   private void xQuery10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	// e.g. "CONPAR"
   	String confID = xtextField1.getText();
   	
   	
   	/*String input = "let $publications := doc('publications.xml')/root "
   			+ "return <root>{ "
   			+ 	"for $p in $publications/proceedings "
   			+ 	"where $p/cid = '" + confID +"' "
   			+ 	"return( "
   			+ 		"for $e in $p/editor "
   			+ 		"return <name><author>{$e/text()}</author></name> "
   			+ 	") "
   			+ "} "
   			+ "{ "
   			+ 	"for $p in $publications/proceedings "
   			+ 	"where $p/cid = '" + confID +"' "
   			+ 	"return ( "
   			+ 		"for $ip in $publications/inproceedings "
   			+ 		"where $ip/pid = $p/id "
   			+ 		"return "
   			+ 			"for $a in $ip/author "
   			+ 			"return <name>{$a}</name> "
   			+ 	") "
   			+ "}</root>";*/
   	
   	String input =
	    	"let $proceedings := doc('proceedings.xml')/root//*[cid/text() = '" + confID + "'], "
			+"$inproceedings := doc('inproceedings.xml')/root//*[pid/text() = $proceedings/id/text()] "
			+"return "
			+  "<root>{ "
			+    "for $author in distinct-values($proceedings/editor/text() | $inproceedings/author/text()) "
			+    "return "
			+      "<author>{ "
			+        "<id>{$author}</id> "
			+      "}</author> "
			+  "}</root> ";
   	
   	
   	Query query = db3.execute(input);
   	
	new ch.ethz.globis.isk.xmldb.Table(
   			db3,
   			null,
   			query,
   			"Names of authors and editors of conference " + confID + ".",
   			new String[] { "Name" },
   			new String[] { "id" },
   			false
   	);
   }                                         

   private void xQuery11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	   String confID = xtextField1.getText();
   	
   	String input =
   			"let $proceedings := doc('proceedings.xml')/root//*[cid/text() = '" + confID + "'], "
   			+ "$inproceedings := doc('inproceedings.xml')/root//*[pid/text() = $proceedings/id/text()] "
   			+ "return <root>{$inproceedings}</root> ";
   		
       	Query query = db3.execute(input);
       	
    	new ch.ethz.globis.isk.xmldb.Table(
       			db3,
       			null,
       			query,
       			"Inproceedings of conference " + confID + ".",
       			new String[] { "ID", "Title", "Proceedings", "Authors" },
       			new String[] { "id", "title", "pid", "author" },
       			false
       	);
   }                                         

   private void xQuery12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	   Query query = db3.executeFile("query12.xq");
   	
		new ch.ethz.globis.isk.xmldb.Table(
   			db3,
   			null,
   			query,
   			"Persons that are author in InProceedings and editor in appropriate Proceedings",
   			new String[] { "Name" },
   			new String[] { "id" },
   			false
   	);
   }  
                                        

   private void xQuery13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	   String authorID = xtextField1.getText();
   	
   	String input =
   			"let $inproceedings :=doc('inproceedings.xml')/root/* "
   			+"return <root>{ "
   			+  "for $ip in $inproceedings "
   			+  "where some $author in $ip/author[last()] satisfies $author/text() = '" + authorID + "' "
   			+  "return $ip "
   			+"}</root> ";
   		
       	Query query = db3.execute(input);
       	
    	new ch.ethz.globis.isk.xmldb.Table(
       			db3,
       			null,
       			query,
       			"Publications where author " + authorID + " appears as last author.",
       			new String[] { "ID", "Title", "Proceedings", "Authors" },
       			new String[] { "id", "title", "pid", "author" },
       			false
       	);
   }                                         

   private void xQuery14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	   int beginYear = 0;
   	int endYear = 0;
   	try {
   		beginYear = Integer.parseInt(xtextField1.getText());
   		endYear = Integer.parseInt(xtextField2.getText());
   	} catch (Exception e) {
   		e.printStackTrace();
   	}
   	
   	if (beginYear > endYear){
   		int temp = beginYear;
   		beginYear = endYear;
   		endYear = temp;
   	}
   	
   	String input =
   			"let $proceedings := doc('proceedings.xml')/root/*[1982 <= ceid and ceid <= 1986], "
   			+"$inproceedings := doc('inproceedings.xml')/root/*, "
   			+"$publishers := "
   			+  "for $p in $proceedings "
   			+  "where every $e in $p/editor satisfies $e/id/text() = $inproceedings/author/id/text() "
   			+  "return $p/publisher "
   			+"return <root>{ "
   			+  "for $publisher in distinct-values($publishers) "
   			+  "return <publisher><id>{$publisher}</id></publisher> "
   			+"}</root> ";
   		
       	Query query = db3.execute(input);
       	
    	new ch.ethz.globis.isk.xmldb.Table(
       			db3,
       			null,
       			query,
       			"Publishers of Proceedings whose authors appear in any InProceedings in range of years",
       			new String[] { "Publisher" },
       			new String[] { "id"  },
       			false
       	);
   }  
   
   
   
   
   

   private void jTextField14MouseClicked(java.awt.event.MouseEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {                                             
       // TODO add your handling code here:
   }                                            

   private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jTextField15MouseClicked(java.awt.event.MouseEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {                                             
       // TODO add your handling code here:
   }                                            

   private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton52ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton57ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton64ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jButton66ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jTextField18MouseClicked(java.awt.event.MouseEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {                                             
       // TODO add your handling code here:
   }                                            

 
   

   private void mpublicationsButtonActionPerformed(ActionEvent evt) {
   	new ch.ethz.globis.isk.mongodb.Table(db2.publications,
				db2.publications.find().iterator(),
   			"Publications",
   			new String[] { "ID", "Title" },
   			new String[] { "_id", "title" },
   			true);
   }
   
   private void mproceedingsButtonActionPerformed(ActionEvent evt) {
	   System.out.println("Opening table ...");
   	new ch.ethz.globis.isk.mongodb.Table(db2.publications,
				db2.publications.find(Filters.exists("publications")).iterator(),
   			"Proceedings",
   			new String[] { "ID", "Title", "Year", "Publisher", "ISBN", "Editors", "Series", "Conference Edition", "Publications" },
   			new String[] { "_id", "title", "year", "publisher", "isbn", "editors", "series", "conferenceEdition", "publications" },
   			true);
   }
   
  

   
   
   
  ///////////////////////////////////XML/////////////////////////////////////////////////////// 
   
   
   private void xPublicationActionPerformed(ActionEvent evt) {
   	new ch.ethz.globis.isk.xmldb.Table(
   			db3,
   			"publications.xml",
   			null,
   			"Publications",
   			new String[] { "ID", "Title" },
   			new String[] { "id", "title" },
   			true
   	);
   }
   
   // Variables declaration - do not modify 
   
   
   
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton4;
   private javax.swing.JButton jButton5;
   private javax.swing.JButton jButton6;
   private javax.swing.JButton jButton7;
   private javax.swing.JButton jButton8;
   private javax.swing.JButton jButton9;
   private javax.swing.JButton jButton10;
   private javax.swing.JButton jButton11;
   private javax.swing.JButton jButton12;
   private javax.swing.JButton jButton13;
   private javax.swing.JButton jButton14;
   private javax.swing.JButton jButton15;
   private javax.swing.JButton jButton16;
   private javax.swing.JButton jButton17;
   private javax.swing.JButton jButton18;
   private javax.swing.JButton jButton19;
   private javax.swing.JButton mPublicationButton;
   private javax.swing.JButton xSerButton;
   private javax.swing.JButton jButton21;
   private javax.swing.JButton jButton22;
   private javax.swing.JButton jButton23;
   private javax.swing.JButton xPublicationButton;
   private javax.swing.JButton xProButton;
   private javax.swing.JButton xInProButton;
   private javax.swing.JButton xConfButton;
   private javax.swing.JButton xConfEdButton;
   private javax.swing.JButton xAuthEdButton;
   private javax.swing.JButton mPreButton;
   private javax.swing.JButton xPublisherButton;
   private javax.swing.JButton xQuery1Button;
   private javax.swing.JButton xQuery2Button;
   private javax.swing.JButton xQuery3Button;
   private javax.swing.JButton xQuery4Button;
   private javax.swing.JButton xQuery9Button;
   private javax.swing.JButton xQuery10Button;
   private javax.swing.JButton xQuery8Button;
   private javax.swing.JButton xQuery11Button;
   private javax.swing.JButton xQuery6Button;
   private javax.swing.JButton xQuery7Button;
   private javax.swing.JButton xQuery5Button;
   private javax.swing.JButton xQuery13Button;
   private javax.swing.JButton xQuery14Button;
   private javax.swing.JButton xQuery12Button;
   private javax.swing.JButton jButton45;
   private javax.swing.JButton jButton46;
   private javax.swing.JButton jButton47;
   private javax.swing.JButton jButton48;
   private javax.swing.JButton jButton49;
   private javax.swing.JButton jButton50;
   private javax.swing.JButton jButton51;
   private javax.swing.JButton jButton52;
   private javax.swing.JButton jButton53;
   private javax.swing.JButton jButton54;
   private javax.swing.JButton jButton55;
   private javax.swing.JButton jButton56;
   private javax.swing.JButton jButton57;
   private javax.swing.JButton jButton58;
   private javax.swing.JButton jButton59;
   private javax.swing.JButton jButton60;
   private javax.swing.JButton jButton61;
   private javax.swing.JButton jButton62;
   private javax.swing.JButton jButton63;
   private javax.swing.JButton jButton64;
   private javax.swing.JButton jButton65;
   private javax.swing.JButton jButton66;

   
   
   
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JPanel jPanel5;
   
   
   private javax.swing.JSeparator jSeparator1;
   private javax.swing.JSeparator jSeparator10;
   private javax.swing.JSeparator jSeparator11;
   private javax.swing.JSeparator jSeparator12;
   private javax.swing.JSeparator jSeparator13;
   private javax.swing.JSeparator jSeparator14;
   private javax.swing.JSeparator jSeparator15;
   private javax.swing.JSeparator jSeparator16;
   private javax.swing.JSeparator jSeparator17;
   private javax.swing.JSeparator jSeparator9;
   private javax.swing.JTextField jTextField10;
   private javax.swing.JTextField xtextField1;
   private javax.swing.JTextField xtextField2;
   private javax.swing.JTextField xtextField3;
   private javax.swing.JTextField jTextField14;
   private javax.swing.JTextField jTextField15;
   private javax.swing.JTextField jTextField18;
   private javax.swing.JTextField jTextField8;
   private javax.swing.JTextField jTextField9;
   // End of variables declaration 
   
}